; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; TCP + VESC (아이폰 연결용)
[env:tcp]
platform = espressif32
board = wt32-eth01
framework = arduino
lib_deps = SolidGeek/VescUart@^1.0.0
monitor_speed = 115200
build_src_filter = +<main_tcp.cpp>

; 시리얼 테스트용
[env:serial-test]
platform = espressif32
board = wt32-eth01
framework = arduino
lib_deps = SolidGeek/VescUart@^1.0.0
monitor_speed = 115200
build_src_filter = +<main_serial.cpp>
